### PR TITLE
Use std::abs() for floating-point tolerance tests

### LINKED ISSUE #641: test_driver.cc fails to build with Apple clang 10.0
qpdf/test_driver.cc:3298:12: error: call to 'abs' is ambiguous
    assert(abs(num - 42.0) < 1e-100);
    
Three instances of abs() should be changed to fabs(), and "#include <math.h>" added.

### PR DESCRIPTION
**Pull request by jaklein**
Fixes #641

### CODE REVIEW

**Comment by jberkenbilt** [comment]
I could rather `#include <cstddef>` and use `std::abs` instead. Could you try that fix?

**Comment by jaklein** [comment]
std::abs is defined in <cmath>, but it works.

**Comment by jberkenbilt** [comment]
I'm going to fix this a different way. Thank for the contribution.
