### ISSUE TITLE
QPDFObjectHandle::QPDFObjectHandle(QPDFObjectHandle const&) constructor no longer present in libqpdf.so

### ISSUE THREAD

**Issue by Lyusternik** [qpdf/qpdf#445]
This change breaks short-form range-based for loops of std::vector<QPDFObjectHandle>, among other things.
```
MyClass:MyFunc(){

  std::vector<QPDFObjectHandle>* page = getPages();
  for (page: pages)//works linking against QPDF 9.1.1, fails against later versions
  {
    doThing();
  }
}
```
[qpdf911-nm.txt](https://github.com/qpdf/qpdf/files/4720714/qpdf911-nm.txt)
[qpdf10-nm.txt](https://github.com/qpdf/qpdf/files/4720715/qpdf10-nm.txt)
nm -gDC output provided for both libraries.
Note at lines 510 in 911 and 526 in 10 - qpdf9.1.1 has a constructor for QPDFObjectHandle::QPDFObjectHandle(QPDFObjectHandle const&), qpdf 10 does not.
When I attempt to compile this code against the new library, I get the following linker error:
```
/usr/bin/ld: ./src/myProg.o: in function `MyClass::myFunc(QPDF*)':
myProg.cpp:(.text+0x741): undefined reference to `QPDFObjectHandle::QPDFObjectHandle(QPDFObjectHandle const&)'
/usr/bin/ld: myProg.cpp:(.text+0x7bc): undefined reference to `QPDFObjectHandle::QPDFObjectHandle(QPDFObjectHandle const&)'
/usr/bin/ld: myProg.cpp:(.text+0x83a): undefined reference to `QPDFObjectHandle::operator=(QPDFObjectHandle const&)'
```

Is this a side effect of the 10.0 performance enhancements that I need to work around, or a regression?

**Comment by jberkenbilt** [comment]
The code snippet isn't a real code snippet that I can actually compile, so I have no way to reproduce this using your code snippet. However, this actual code snippet works fine with qpdf 10.0.1:

```c++
#include <qpdf/QPDFObjectHandle.hh>
#include <qpdf/QPDF.hh>

int main()
{
    QPDF pdf;
    pdf.processFile("/tmp/a.pdf");
    std::vector<QPDFObjectHandle> pages = pdf.getAllPages();
    for (auto page: pages)
    {
        std::cout << page.isDictionary() << std::endl;
    }
    return 0;
}
```
The qpdf library uses operator= and copy constructor for QPDFObjectHandle quite extensively. They definitely work. There must be something else going on. Relevant information would include what OS/compiler (including version) you're using, whether you're using an OS package or building it yourself, and how you're compiling/linking your code. Also note that 9.1.1 and 10.0.0 are not binary compatible, so you have to recompile, not just relink, to move from one version to another. qpdf uses semantic versioning, so across major versions, there's no linker compatibility. You do need to be using a compiler that supports C++11. The copy constructor and operator= are declared with `= default`, which is a C++11 feature.

**Comment by jberkenbilt** [comment]
Glad it's working. Thanks for following up.
