### ISSUE TITLE
test_driver.cc fails to build with Apple clang 10.0

### ISSUE THREAD

**Issue by jaklein** [qpdf/qpdf#641]
qpdf/test_driver.cc:3298:12: error: call to 'abs' is ambiguous
    assert(abs(num - 42.0) < 1e-100);
    
Three instances of abs() should be changed to fabs(), and "#include <math.h>" added.
