### ISSUE TITLE
Failed to compile on macOS High Sierra (10.13)

### ISSUE THREAD

**Issue by t246246** [qpdf/qpdf#158]
For some reason, g++ (clang) failed to find libraries just built:
```
/bin/bash ./libtool --mode=link g++ -g -O2 -Wold-style-cast -Wall libtests/build/dct_compress.o -o libtests/build/dct_compress -ljpeg -lz  -lqpdf -L/opt/local/lib -Llibqpdf/build
libtool: link: g++ -g -O2 -Wold-style-cast -Wall libtests/build/dct_compress.o -o libtests/build/dct_compress -Wl,-bind_at_load  -ljpeg -lz -lqpdf -L/opt/local/lib -Llibqpdf/build
Undefined symbols for architecture x86_64:
  "QUtil::string_to_int(char const*)", referenced from:
      _main in dct_compress.o
  "Pl_DCT::write(unsigned char*, unsigned long)", referenced from:
      _main in dct_compress.o
  "Pl_DCT::finish()", referenced from:
      _main in dct_compress.o
  "Pl_DCT::Pl_DCT(char const*, Pipeline*, unsigned int, unsigned int, int, J_COLOR_SPACE, Pl_DCT::CompressConfig*)", referenced from:
      _main in dct_compress.o
  "Pl_DCT::~Pl_DCT()", referenced from:
      _main in dct_compress.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libtests/build/dct_compress] Error 1
```

As I do not understand your configure/macros, I can not send a patch; All I can do now is just let you know I have to change your build.mk files (at examples/libtests/qpdf) like this:
```
-      $(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS) $(LDFLAGS_libqpdf),$(LIBS_libqpdf) $(LIBS))))
+      $(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS) $(LDFLAGS_libqpdf),libqpdf/build/libqpdf.la)))
```

Best Wishes,

**Comment by jberkenbilt** [comment]
Looks to me like you're just not linking with the jpeg library. Make sure you have the jpeg library installed in a place where your build can find it.

**Comment by t246246** [comment]
No jpeg library is /opt/local/lib, installed from MacPort. Missing function in linking is QUtil::string_to_int(char const*).

**Comment by jberkenbilt** [comment]
Got it, thanks. I don't know why this should be necessary, but other people have made similar reports. Maybe I'm constructing my compile statements wrong or something. I'll see if I can figure it out when I get a chance. Thanks for taking the trouble to report and clarify.

**Comment by t246246** [comment]
Now I understand what is happening.  I installed qpdf-6.0.0 via MacPort at /opt/local/lib.
So ld program find that libqpdf.dylib first.  Unfortunately, libjpeg is also there, and I cannot remove '-L/opt/local/lib' from option list.  I don't know why ld looks /opt/local/lib first and find no way to change that order...  Anyway, uninstalling qpdf-6.0.0 from MacPort and then compile qpdf 7.0.0, all goes well.

**Comment by t246246** [comment]
Looking the output 
```/bin/bash ./libtool --mode=link g++ -g -O2 -Wold-style-cast -Wall libtests/build/dct_compress.o -o libtests/build/dct_compress -ljpeg -lz  -lqpdf -L/opt/local/lib -Llibqpdf/build```

It's simply because -L/opt/local/lib is before -Llibqpdf/build. So I change the order as follows:
```
diff --git a/examples/build.mk b/examples/build.mk
index bd2119a..518f4d5 100644
--- a/examples/build.mk
+++ b/examples/build.mk
@@ -39,4 +39,4 @@ $(foreach B,$(CBINS_examples),$(eval \
 
 $(foreach B,$(BINS_examples) $(CBINS_examples),$(eval \
   examples/$(OUTPUT_DIR)/$(call binname,$(B)): $(OBJS_$(B)) ; \
-	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS) $(LDFLAGS_libqpdf),$(LIBS_libqpdf) $(LIBS))))
+	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS_libqpdf) $(LDFLAGS),$(LIBS_libqpdf) $(LIBS))))
diff --git a/libtests/build.mk b/libtests/build.mk
index baa3412..99942c1 100644
--- a/libtests/build.mk
+++ b/libtests/build.mk
@@ -43,4 +43,4 @@ $(foreach B,$(BINS_libtests),$(eval \
 
 $(foreach B,$(BINS_libtests),$(eval \
   libtests/$(OUTPUT_DIR)/$(call binname,$(B)): $(OBJS_$(B)) ; \
-	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS) $(LDFLAGS_libqpdf),$(LIBS) $(LIBS_libqpdf))))
+	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS_libqpdf) $(LDFLAGS),$(LIBS) $(LIBS_libqpdf))))
diff --git a/qpdf/build.mk b/qpdf/build.mk
index e3d5097..893bbbd 100644
--- a/qpdf/build.mk
+++ b/qpdf/build.mk
@@ -30,4 +30,4 @@ $(foreach B,$(CBINS_qpdf),$(eval \
 
 $(foreach B,$(BINS_qpdf) $(CBINS_qpdf),$(eval \
   qpdf/$(OUTPUT_DIR)/$(call binname,$(B)): $(OBJS_$(B)) ; \
-	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS) $(LDFLAGS_libqpdf),$(LIBS_libqpdf) $(LIBS))))
+	$(call makebin,$(OBJS_$(B)),$$@,$(LDFLAGS_libqpdf) $(LDFLAGS),$(LIBS_libqpdf) $(LIBS))))
```
I think this would be no harm for other situations.

**Comment by jberkenbilt** [comment]
Yes, I think you are correct. I'll test and likely accept your proposed change as is. They way it's in there now looks wrong. I must have been having a bad brain day when I wrote that. Thanks!

**Comment by ryandesign** [comment]
I agree that is the correct fix; I just verified the issue and the proposed fix, after a user [reported this problem](https://trac.macports.org/ticket/55675) to MacPorts. Could the fix be committed, please?
