### ISSUE TITLE
QUtil.cc build error on FreeBSD

### ISSUE THREAD

**Issue by wenheping** [qpdf/qpdf#515]
I failed build QUtils.cc with clang-10, the build log say:

...
libqpdf/QUtil.cc: In function 'QUtil::QPDFTime QUtil::get_current_qpdf_time()':
libqpdf/QUtil.cc:908:47: error: invalid operands of types 'char*(int, int)' and 'int' to binary 'operator/'
  908 |                     static_cast<int>(timezone / 60));
      |                                      ~~~~~~~~ ^ ~~
      |                                      |          |
      |                                      |          int
      |                                      char*(int, int)
...

Any suggestions ?

**Comment by dreua** [comment]
Could you formal the compiler log as code block? Just replace the tree dots with three ` before and after the block or use the code block button. My commit can be hidden once done.

**Comment by dreua** [comment]
Context: https://github.com/qpdf/qpdf/blob/a77f58142d07c5482c90f5ce0e3dbb9c98451c2a/libqpdf/QUtil.cc#L908

**Comment by jberkenbilt** [comment]
I build with clang 10 on Ubuntu 20.04, and it works fine. Unfortunately, `timezone` is a global variable defined in the C library. For some reason, for you, there's probably a `char* timezone(int, int)` function somehow in scope at this point in the compilation of QUtil.cc. I'm not sure why. It's possible that adding `extern long int timezone;` somewhere would cause clang to give a more useful error message, but that's a guess. I'm not sure why this would be different on your system. What exact OS and compiler version are you using?

**Comment by wenheping** [comment]
> 
> 
> I build with clang 10 on Ubuntu 20.04, and it works fine. Unfortunately, `timezone` is a global variable defined in the C library. For some reason, for you, there's probably a `char* timezone(int, int)` function somehow in scope at this point in the compilation of QUtil.cc. I'm not sure why. It's possible that adding `extern long int timezone;` somewhere would cause clang to give a more useful error message, but that's a guess. I'm not sure why this would be different on your system. What exact OS and compiler version are you using?

I know why I failed, I run on FreeBSD.
Thank you !

**Comment by jberkenbilt** [comment]
It would be nice if it worked on FreeBSD. If you figure out what's wrong, I'd welcome a patch, or maybe I can try to spin up a FreeBSD VM and reproduce it.

**Comment by wenheping** [comment]
I can build it on FreeBSD with this patch:

--- libqpdf/QUtil.cc.orig       2021-04-05 06:10:36 UTC
+++ libqpdf/QUtil.cc
@@ -905,7 +905,7 @@ QUtil::get_current_qpdf_time()
                     static_cast<int>(ltime.tm_hour),
                     static_cast<int>(ltime.tm_min),
                     static_cast<int>(ltime.tm_sec),
-                    static_cast<int>(timezone / 60));
+                    static_cast<int>(ltime.tm_gmtoff / 60));
 #endif
 }

would you have a test ?

**Comment by jberkenbilt** [comment]
@wenheping This is helpful. I can create an autoconf test for it and make sure it works by running FreeBSD on a vm. I'll make sure this is fixed for the next qpdf released. When the fix is in master, you will know because I will close this issue with the commit. Thanks!

**Comment by jberkenbilt** [comment]
This patch is not quite right -- the sign of ltime.tm_gmtoff is opposite that of timezone and also opposite of what is needed for this function. However, I am about to commit a correct fix. Thanks for drawing this to my attention!
