### ISSUE TITLE
Can not compile with g++ version: 15.0.1 20250117 (experimental), but this may be a false positive

### ISSUE THREAD

**Issue by rubyFeedback** [qpdf/qpdf#1332]
[ 87%] Building CXX object examples/CMakeFiles/pdf-npages.dir/pdf-npages.cc.o
    [ 88%] Linking CXX executable qpdf-ctest
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc: In function ‘void do_inttypes()’:
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:75:16: error: ‘uint8_t’ was not declared in this scope
     75 | check_size<uint8_t>(1, false);
     | ^~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:10:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
     9 | #include <regex>
     +++ |+#include <cstdint>
     10 | #include <type_traits>
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:75:24: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     75 | check_size<uint8_t>(1, false);
     | ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:75:24: note: there is 1 candidate
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate 1: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:75:24: error: template argument 1 is invalid
     75 | check_size<uint8_t>(1, false);
     | ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:77:16: error: ‘uint16_t’ was not declared in this scope
     77 | check_size<uint16_t>(2, false);
     | ^~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:77:16: note: ‘uint16_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:77:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     77 | check_size<uint16_t>(2, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:77:25: note: there is 1 candidate
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate 1: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:77:25: error: template argument 1 is invalid
     77 | check_size<uint16_t>(2, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:79:16: error: ‘uint32_t’ was not declared in this scope
     79 | check_size<uint32_t>(4, false);
     | ^~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:79:16: note: ‘uint32_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:79:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     79 | check_size<uint32_t>(4, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:79:25: note: there is 1 candidate
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate 1: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:79:25: error: template argument 1 is invalid
     79 | check_size<uint32_t>(4, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:81:16: error: ‘uint64_t’ was not declared in this scope
     81 | check_size<uint64_t>(8, false);
     | ^~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:81:16: note: ‘uint64_t’ is defined in header ‘<cstdint>’; this is probably fixable by adding ‘#include <cstdint>’
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:81:25: error: no matching function for call to ‘check_size<<expression error> >(int, bool)’
     81 | check_size<uint64_t>(8, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:81:25: note: there is 1 candidate
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: candidate 1: ‘template<class T> void check_size(size_t, bool)’
     63 | check_size(size_t size, bool is_signed)
     | ^~~~~~~~~~
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:63:1: note: template argument deduction/substitution failed:
    /home/x/Temp/rbt/qpdf-11.9.1/libtests/cxx11.cc:81:25: error: template argument 1 is invalid
     81 | check_size<uint64_t>(8, false);
     | ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
    [ 88%] Built target qpdf-ctest
    [ 88%] Linking CXX executable test_tokenizer
    [ 88%] Building CXX object examples/CMakeFiles/pdf-overlay-page.dir/pdf-overlay-page.cc.o
    [ 88%] Built target test_tokenizer
    [ 89%] Building CXX object examples/CMakeFiles/pdf-parse-content.dir/pdf-parse-content.cc.o
    [ 90%] Linking CXX executable test_xref
    [ 90%] Built target test_xref
    [ 90%] Building CXX object examples/CMakeFiles/pdf-set-form-values.dir/pdf-set-form-values.cc.o
    [ 90%] Linking CXX executable pdf-npages
    [ 90%] Linking CXX executable pdf-double-page-size
    [ 90%] Linking CXX executable pdf-mod-info
    [ 91%] Linking CXX executable pdf-name-number-tree
    [ 91%] Linking CXX executable pdf-invert-images
    make[2]: *** [libtests/CMakeFiles/cxx11.dir/build.make:79: libtests/CMakeFiles/cxx11.dir/cxx11.cc.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:1258: libtests/CMakeFiles/cxx11.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 91%] Built target pdf-npages
    [ 91%] Built target pdf-double-page-size
    [ 91%] Linking CXX executable pdf-filter-tokens
    [ 91%] Built target pdf-name-number-tree
    [ 91%] Built target pdf-mod-info
    [ 91%] Built target pdf-invert-images
    [ 91%] Built target pdf-filter-tokens
    [ 91%] Linking CXX executable pdf-overlay-page
    [ 91%] Linking CXX executable pdf-parse-content
    [ 91%] Built target pdf-overlay-page
    [ 91%] Built target pdf-parse-content
    [ 91%] Linking CXX executable pdf-set-form-values
    [ 91%] Built target pdf-set-form-values
    [ 91%] Linking CXX executable fix-qdf
    [ 91%] Built target fix-qdf
    [ 91%] Linking CXX executable test_driver
    [ 91%] Built target test_driver
    make: *** [Makefile:166: all] Error 2

**Comment by rubyFeedback** [comment]
I just checked with the latest git checkout of qpdf, and it compiles fine. So closing this (I think I ran into a similar problem before; perhaps it may be time for a new stable release of qpdf. I keep on using the older one.)

**Comment by jberkenbilt** [comment]
@rubyFeedback It is time for a new stable release of qpdf. We are working on that.
