### ISSUE TITLE
cmake build issues on amazon linux 2 machine 

### ISSUE THREAD

**Issue by kshunjan26** [qpdf/qpdf#1149]
I am trying to install latest version of qpdf on one of our amazon linux 2 server.
I have following dependencies installed:

- gcc gcc-c++  version 7.3.1
- zlib-devel version 1.2.7
- libjpeg-turbo-devel version 2.0.90
- gnutls-devel version 3.3.29
- openssl-devel version 1.10.2k
- cmake version 3.28.3 for build

When I run: `cmake -S . -B build` it gives through successfully.
But when I run this command `cmake --build build` it gives me this error

`[ 23%] Building CXX object libqpdf/CMakeFiles/libqpdf_object.dir/qpdflogger-c
.cc.o
[ 23%] Building CXX object libqpdf/CMakeFiles/libqpdf_object.dir/QPDFCrypto_o
penssl.cc.o
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In constructor ‘QPDFCr
ypto_openssl::QPDFCrypto_openssl()’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:98:12: error: ‘EVP_MD_C
TX_new’ was not declared in this scope
     md_ctx(EVP_MD_CTX_new()),
            ^~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:98:12: note: suggested 
alternative: ‘EVP_MD_CTX_init’
     md_ctx(EVP_MD_CTX_new()),
            ^~~~~~~~~~~~~~
            EVP_MD_CTX_init
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In destructor ‘virtual
 QPDFCrypto_openssl::~QPDFCrypto_openssl()’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:108:5: error: ‘EVP_MD_C
TX_reset’ was not declared in this scope
     EVP_MD_CTX_reset(md_ctx);
     ^~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:108:5: note: suggested 
alternative: ‘EVP_MD_CTX_create’
     EVP_MD_CTX_reset(md_ctx);
     ^~~~~~~~~~~~~~~~
     EVP_MD_CTX_create
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:109:5: error: ‘EVP_CIPH
ER_CTX_reset’ was not declared in this scope
     EVP_CIPHER_CTX_reset(cipher_ctx);
     ^~~~~~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:109:5: note: suggested 
alternative: ‘EVP_CIPHER_CTX_free’
     EVP_CIPHER_CTX_reset(cipher_ctx);
     ^~~~~~~~~~~~~~~~~~~~
     EVP_CIPHER_CTX_free
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:111:5: error: ‘EVP_MD_C
TX_free’ was not declared in this scope
     EVP_MD_CTX_free(md_ctx);
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:111:5: note: suggested 
alternative: ‘EVP_MD_CTX_create’
     EVP_MD_CTX_free(md_ctx);
     ^~~~~~~~~~~~~~~
     EVP_MD_CTX_create
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::MD5_init()’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:123:19: error: ‘EVP_MD_
CTX_reset’ was not declared in this scope
     check_openssl(EVP_MD_CTX_reset(md_ctx));
                   ^~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:123:19: note: suggested
 alternative: ‘EVP_MD_CTX_create’
     check_openssl(EVP_MD_CTX_reset(md_ctx));
                   ^~~~~~~~~~~~~~~~
                   EVP_MD_CTX_create
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::SHA2_init(int)’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:146:19: error: ‘EVP_MD_
CTX_reset’ was not declared in this scope
     check_openssl(EVP_MD_CTX_reset(md_ctx));
                   ^~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:146:19: note: suggested
 alternative: ‘EVP_MD_CTX_create’
     check_openssl(EVP_MD_CTX_reset(md_ctx));
                   ^~~~~~~~~~~~~~~~
                   EVP_MD_CTX_create
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::RC4_init(const unsigned char*, int)’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:208:19: error: ‘EVP_CIP
HER_CTX_reset’ was not declared in this scope
     check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                   ^~~~~~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:208:19: note: suggested
 alternative: ‘EVP_CIPHER_CTX_free’
     check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                   ^~~~~~~~~~~~~~~~~~~~
 EVP_CIPHER_CTX_free
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::rijndael_init(bool, const unsigned char*, size
_t, bool, unsigned char*)’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:238:19: error: ‘EVP_CIP
HER_CTX_reset’ was not declared in this scope
     check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                   ^~~~~~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:238:19: note: suggested
 alternative: ‘EVP_CIPHER_CTX_free’
     check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                   ^~~~~~~~~~~~~~~~~~~~
                   EVP_CIPHER_CTX_free
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::RC4_finalize()’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:263:23: error: ‘EVP_CIP
HER_CTX_reset’ was not declared in this scope
         check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                       ^~~~~~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:263:23: note: suggested
 alternative: ‘EVP_CIPHER_CTX_free’
         check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                       ^~~~~~~~~~~~~~~~~~~~
                       EVP_CIPHER_CTX_free
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc: In member function ‘vi
rtual void QPDFCrypto_openssl::rijndael_finalize()’:
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:271:23: error: ‘EVP_CIP
HER_CTX_reset’ was not declared in this scope
         check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                       ^~~~~~~~~~~~~~~~~~~~
/home/admin/qpdf-11.8.0/libqpdf/QPDFCrypto_openssl.cc:271:23: note: suggested
 alternative: ‘EVP_CIPHER_CTX_free’
         check_openssl(EVP_CIPHER_CTX_reset(cipher_ctx));
                       ^~~~~~~~~~~~~~~~~~~~
                       EVP_CIPHER_CTX_free
gmake[2]: *** [libqpdf/CMakeFiles/libqpdf_object.dir/QPDFCrypto_openssl.cc.o]
 Error 1
gmake[1]: *** [libqpdf/CMakeFiles/libqpdf_object.dir/all] Error 2
gmake: *** [all] Error 2`

**Comment by jberkenbilt** [comment]
Amazon Linux 2's toolchain is too old to build the current version of qpdf. You need a compiler that supports c++17. Amazon Linux 2 is nearing end of life. If possible, use a newer Amazon Linux. If not possible, you may need a more recent gcc or clang. It is also possible to build with Ubuntu 18.04 and copy the shared libraries across as is done with the Linux binary version available from the releases page. Ubuntu 18.04 has a new enough compiler and an old enough libstdc++ to work with Amazon Linux 2. I don't have any specific knowledge about how you can get a more up-to-date compiler toolchain on Amazon Linux 2, but I suspect you can find this with a search.

**Comment by jberkenbilt** [comment]
Now that I've said all that, maybe I'm wrong and the problem is your openssl setup. It's possible that you may have either too old a version of openssl or conflicting versions installed. I'm not sure what the oldest openssl that works with qpdf is, but I've probably never built it with older than 1.1. You can try gnutls, or you can use native crypto. Using native crypto is not recommended from a security standpoint since qpdf's native crypto doesn't get the focus and attention of openssl or gnutls, but there are no known issues with it, and for now, it works functionally. I may eventually drop qpdf's native crypto as I add features that require a crypto library, but for now, it is still usable.

**Comment by rubyFeedback** [comment]
kshunjan26: I think that problem has to do with openssl. If you lack permissions on the system you can perhaps try to compile openssl etc... into your home directory (where you should have permissions) and check whether you can use it; LD_LIBRARY_PATH (https://unix.stackexchange.com/questions/425251/using-ldconfig-and-ld-so-conf-versus-ld-library-path).

Instructions you may adapt from e. g. https://www.linuxfromscratch.org/lfs/view/development/chapter08/openssl.html.

So with a more recent openssl, you can test and check to see whether qpdf builds against it (may have to pass specific options to have qpdf find it).

On my system I have very recent software compiled, and there qpdf works very well, so the problem is somewhere in the compile chain on that  amazon linux 2 server.

Interesting that "cmake -S . -B build" compiles successfully though, can you start qpdf there? Perhaps it may not run.
